import { useState } from 'react';
import { Container } from 'react-bootstrap';
import { Link, useNavigate } from 'react-router-dom';
import { useT } from '../../hooks/useT';

import arrow from '../../assets/images/iconos/arrow.png'

const ES = {
  title: "TÉRMINOS DE SERVICIO DE BRICKLY",
  intro: "LEA CUIDADOSAMENTE: El acceso, registro o utilización de la plataforma digital denominada BRICKLY (la Plataforma), operada por FUNDAMENTO SH S.A., sociedad constituida conforme a las leyes de la República de Guatemala, implica la aceptación plena, expresa y sin reservas de los presentes Términos y Condiciones, la Política de Privacidad y cualquier política adicional publicada (conjuntamente, el Acuerdo). Si el Usuario no está de acuerdo, deberá abstenerse inmediatamente de utilizar la Plataforma.",
  sections: [
    {
      num: "1.",
      title: "DEFINICIONES E INTERPRETACIÓN",
      intro: "Para efectos del presente Acuerdo, los términos en mayúscula inicial tendrán los significados que se detallan a continuación, ya sea que se utilicen en singular o plural:",
      items: [
        { num: "1.1.", bold: "Brickly o La Compañía", text: " significa FUNDAMENTO SH S.A., sociedad constituida conforme a las leyes de la República de Guatemala, incluyendo sus matrices, subsidiarias, afiliadas, directores, administradores, representantes, empleados, contratistas y cesionarios." },
        { num: "1.2.", bold: "Plataforma", text: " significa el ecosistema tecnológico integral operado por Brickly, incluyendo, sin limitación, el sitio web, aplicaciones móviles, software, código fuente y código objeto, interfaces de programación (APIs), bases de datos, servidores, infraestructura en la nube, algoritmos, interfaces gráficas, sistemas de comunicación, herramientas de gestión, paneles administrativos, funcionalidades presentes o futuras y cualquier otro medio o componente digital mediante el cual se ofrezcan los Servicios." },
        { num: "1.3.", bold: "Servicios", text: " significa cualquier funcionalidad, herramienta, módulo, producto digital, servicio de suscripción, sistema de publicación, promoción, análisis, verificación, gestión, intermediación tecnológica o cualquier prestación proporcionada por Brickly a través de la Plataforma, ya sea de carácter gratuito o remunerado." },
        { num: "1.4.", bold: "Usuario", text: " significa toda persona individual o jurídica que acceda, navegue, consulte, utilice o se registre en la Plataforma bajo cualquier modalidad, incluyendo visitantes no registrados, usuarios registrados, suscriptores de pago, representantes corporativos o terceros autorizados." },
        { num: "1.5.", bold: "Contenido y Contenido del Usuario", text: " se entenderá por Contenido cualquier información, dato, texto, imagen, fotografía, video, render, plano, documento, anuncio, mensaje, precio, archivo, logotipo o material de cualquier naturaleza incorporado, transmitido o mostrado a través de la Plataforma. Contenido del Usuario significa todo Contenido cargado, publicado, enviado, compartido o generado directa o indirectamente por el Usuario, bajo su exclusiva responsabilidad." },
        { num: "1.6.", bold: "Membresía, Suscripción o Servicios de Pago", text: " significa cualquier plan contractual que otorgue acceso a funcionalidades premium o ampliadas de la Plataforma a cambio del pago periódico o único de tarifas, comisiones o cargos establecidos por Brickly, sujeto a renovación automática y a las condiciones comerciales aplicables." },
        { num: "1.7.", bold: "Datos Personales y Datos Resultantes", text: " Datos Personales significa cualquier información que identifique o pueda identificar directa o indirectamente a una persona individual, conforme a la legislación aplicable. Datos Resultantes o Datos Agregados significa información anonimizada, estadística, analítica o derivada generada por Brickly a partir del uso de la Plataforma, que no permite la identificación individual de Usuarios o transacciones específicas y cuya titularidad corresponderá exclusivamente a Brickly." },
        { num: "1.8.", bold: "Inmueble o Propiedad", text: " significa cualquier bien inmueble, derecho real, proyecto inmobiliario, desarrollo, unidad, lote, terreno, construcción, activo inmobiliario o expectativa legítima de adquisición, comercialización o explotación que sea publicado, promocionado o negociado a través de la Plataforma." },
        { num: "1.9.", bold: "Reglas de Interpretación", text: " Salvo disposición expresa en contrario: a) los encabezados tienen fines meramente referenciales y no afectarán la interpretación del Acuerdo; b) el singular incluye el plural y viceversa; c) el término 'incluye' se entenderá como 'incluye sin limitación'; d) cualquier referencia a leyes comprenderá sus reformas vigentes; y e) cualquier ambigüedad se interpretará de la manera que mejor preserve la validez del Acuerdo y limite la responsabilidad de Brickly en la máxima medida permitida por la ley." }
      ]
    }
  ]
};

const EN = {
  title: "BRICKLY TERMS OF SERVICE",
  intro: "READ CAREFULLY: Accessing, registering, or using the digital platform known as BRICKLY (the Platform), operated by FUNDAMENTO SH S.A, a company incorporated under the laws of the Republic of Guatemala, implies full, express, and unreserved acceptance of these Terms and Conditions, the Privacy Policy, and any additional published policies (collectively, the Agreement). If the User does not agree, they must immediately refrain from using the Platform.",
  sections: [
    {
      num: "1.",
      title: "DEFINITIONS AND INTERPRETATION",
      intro: "For purposes of this Agreement, capitalized terms shall have the meanings set forth below, whether used in singular or plural:",
      items: [
        { num: "1.1.", bold: "Brickly or The Company", text: " means FUNDAMENTO SH S.A, a company incorporated under the laws of the Republic of Guatemala, including its parent companies, subsidiaries, affiliates, directors, managers, representatives, employees, contractors, and assignees." },
        { num: "1.2.", bold: "Platform", text: " means the comprehensive technological ecosystem operated by Brickly, including, without limitation, the website, mobile applications, software, source code and object code, application programming interfaces (APIs), databases, servers, cloud infrastructure, algorithms, graphical interfaces, communication systems, management tools, administrative panels, present or future functionalities, and any other digital medium or component through which the Services are offered." },
        { num: "1.3.", bold: "Services", text: " means any functionality, tool, module, digital product, subscription service, publication system, promotion, analysis, verification, management, technological intermediation, or any service provided by Brickly through the Platform, whether free of charge or for a fee." },
        { num: "1.4.", bold: "User", text: " means any individual or legal entity that accesses, browses, consults, uses, or registers on the Platform in any capacity, including unregistered visitors, registered users, paying subscribers, corporate representatives, or authorized third parties." },
        { num: "1.5.", bold: "Content and User Content", text: " Content means any information, data, text, image, photograph, video, render, floor plan, document, advertisement, message, price, file, logo, or material of any nature incorporated, transmitted, or displayed through the Platform. User Content means all Content uploaded, published, sent, shared, or generated directly or indirectly by the User, under their exclusive responsibility." },
        { num: "1.6.", bold: "Membership, Subscription, or Paid Services", text: " means any contractual plan that grants access to premium or expanded Platform functionalities in exchange for periodic or one-time payment of fees, commissions, or charges established by Brickly, subject to automatic renewal and applicable commercial conditions." },
        { num: "1.7.", bold: "Personal Data and Resulting Data", text: " Personal Data means any information that identifies or may directly or indirectly identify an individual, in accordance with applicable law. Resulting Data or Aggregated Data means anonymized, statistical, analytical, or derived information generated by Brickly from the use of the Platform, which does not allow individual identification of Users or specific transactions, and whose ownership belongs exclusively to Brickly." },
        { num: "1.8.", bold: "Property or Real Estate", text: " means any real property, real right, real estate project, development, unit, lot, land, construction, real estate asset, or legítimate expectation of acquisition, commercialization, or exploitation that is published, promoted, or negotiated through the Platform." },
        { num: "1.9.", bold: "Rules of Interpretation", text: " Unless expressly stated otherwise: a) headings are for reference purposes only and shall not affect the interpretation of the Agreement; b) the singular includes the plural and vice versa; c) the term includes shall be understood as includes without limitation; d) any reference to laws shall include their current amendments; and e) any ambiguity shall be interpreted in the manner that best preserves the validity of the Agreement and limits Brickly liability to the maximum extent permitted by law." }
      ]
    }
  ]
};

// Sections 2-12 shared structure (ES)
const ES_SECTIONS_2_12 = [
  {
    num: "2.",
    title: "SERVICIOS Y CONDICIONES DE ACCESO",
    items: [
      { num: "2.1.", bold: "Clasificación de Usuarios.", text: " El acceso a la Plataforma se rige por las siguientes categorías: (a) Usuarios Gratuitos, que utilizan la versión básica de los Servicios con acceso a un conjunto limitado de características en comparación con los Usuarios Autorizados, pudiendo obtener acceso a funcionalidades extendidas mediante la adquisición de Servicios de Pago específicos; y (b) Usuarios Autorizados, que utilizan la Plataforma como parte de un plan de Suscripción pagada. Esta última categoría se sub-divide en Administradores, con facultades para gestionar la suscripción y supervisar las actividades de otros usuarios dentro de su organización, y Autorizados Regulares, con facultades para la publicación y gestión de inventario, sujeto siempre al cumplimiento de las especificaciones técnicas de la Compañía." },
      { num: "2.2.", bold: "Licencia de Uso y Estándares de Publicación.", text: " Sujeto al cumplimiento estricto de este Acuerdo, la Compañía otorga al Usuario una licencia limitada, revocable, no exclusiva y no transferible para utilizar los Servicios. El Usuario se obliga a que todo Contenido cargado cumpla estrictamente con las especificaciones técnicas de Brickly, las cuales incluyen, de forma enunciativa pero no limitativa: (i) resolución mínima de imágenes de 1920x1080 pixeles, (ii) ausencia total de marcas de agua de terceros, y (iii) veracidad comprobable de los datos técnicos del Inmueble. El incumplimiento de estas especificaciones se considerará un uso fuera del alcance de la licencia otorgada, facultando a la Compañía para remover el contenido o suspender el acceso." },
      { num: "2.3.", bold: "Propiedad Intelectual y Reserva de Derechos.", text: " La Compañía es la titular única y exclusiva de todos los derechos, títulos e intereses sobre la Plataforma y los Servicios, incluyendo software, código fuente, algoritmos de procesamiento de datos, sistemas de recomendación, arquitectura de bases de datos, diseño de interfaz (UX/UI), elementos gráficos y metodologías de análisis financiero integradas. El Usuario tiene estrictamente prohibido realizar ingeniería inversa, descompilar o intentar extraer el código fuente de la Plataforma. Asimismo, se prohíbe la extracción automatizada de datos (scraping) mediante robots o software externo, así como la creación de obras derivadas que compitan con la Plataforma utilizando elementos propiedad de la Compañía." },
      { num: "2.4.", bold: "Régimen de los Datos Resultantes.", text: " En virtud de la capacidad analítica de la Plataforma, el Usuario reconoce que la Compañía genera información estratégica a partir del uso de los Servicios. La propiedad de estos Datos Resultantes, que comprenden datos estadísticos, tendencias de mercado, volúmenes de transacción y comportamiento analítico, pertenece exclusivamente a la Compañía. El Usuario cede de manera perpetua e irrevocable cualquier derecho sobre dichos datos, facultando a la Compañía para explotarlos comercialmente en la creación de informes de inteligencia de mercado, optimización de modelos de costos y mejora del rendimiento operativo." },
      { num: "2.5.", bold: "Suspensión y Terminación de los Servicios.", text: " La Compañía se reserva la facultad de suspender, rescindir o denegar de manera inmediata el acceso y uso de la Plataforma a cualquier Usuario, sin incurrir en obligación o responsabilidad alguna ni derecho a indemnización, cuando se presente cualquiera de los siguientes supuestos: (a) por estricto cumplimiento de una orden judicial, administrativa o requerimiento gubernamental, o ante cambios legislativos y regulatorios que tornen ilícita o impracticable la prestación de los Servicios; (b) ante la determinación discrecional de la Compañía de que el Usuario ha incumplido cualquier disposición del presente Acuerdo, ha excedido el alcance de la licencia de uso otorgada o ha utilizado la Plataforma con fines no autorizados, fraudulentos o ilegales que comprometan la integridad del ecosistema; y (c) por el impago de las tarifas correspondientes en sus fechas de vencimiento o ante la recepción de notificaciones de contracargos (chargebacks) y disputas financieras relacionadas con la cuenta del Usuario, en cuyo caso la suspensión persistirá hasta la resolución definitiva de la incidencia a entera satisfacción de la Compañía." }
    ]
  },
  {
    num: "3.",
    title: "RESTRICCIONES DE USO",
    items: [
      { num: "3.1.", bold: "Restricciones de Uso.", text: " El Usuario tiene prohibido permitir que cualquier persona acceda o utilice los Servicios, salvo lo dispuesto expresamente en este Acuerdo. En particular, pero no exclusivamente, el Usuario se obliga a: (a) no poner los Servicios a disposición de terceros no autorizados ni utilizarlos en beneficio de personas ajenas a su organización o afiliados; (b) abstenerse de alquilar, sublicenciar, revender, ceder, distribuir o explotar comercialmente los Servicios, incluyendo la práctica de permitir que empleados o colaboradores accedan como invitados para eludir la adquisición de Suscripciones individuales; (c) no realizar ingeniería inversa, copiar, modificar, adaptar, hackear o interferir con la integridad de los Servicios; (d) no acceder a los Servicios, documentación o información confidencial de la Compañía con el propósito de construir, diseñar o promover un producto o servicio competitivo; (e) no compartir credenciales de acceso entre múltiples individuos, salvo para la reasignación formal de una suscripción a un nuevo Usuario Autorizado que reemplace definitivamente a uno previo; (f) no dañar, deshabilitar, sobrecargar o perjudicar la infraestructura tecnológica o la provisión de los Servicios por parte de la Compañía; y (g) no utilizar la Plataforma para fines que infrinjan derechos de propiedad intelectual de terceros o cualquier legislación vigente." },
      { num: "3.2.", bold: "Sanciones.", text: " Los Servicios se ofrecen exclusivamente a usuarios que no son objeto de ningún régimen de sanciones internacionales y que no residen ni acceden a la Plataforma desde jurisdicciones donde dicho acceso esté prohibido por leyes de control de exportaciones o tratados internacionales. Al utilizar los Servicios, el Usuario declara y garantiza que cumple con estos requisitos de cumplimiento. La Compañía se reserva el derecho de limitar, restringir o bloquear en cualquier momento la disponibilidad de los Servicios a cualquier persona, entidad, área geográfica o jurisdicción específica para asegurar el cumplimiento legal y la integridad operativa del ecosistema." }
    ]
  },
  {
    num: "4.",
    title: "OBLIGACIONES DEL USUARIO",
    items: [
      { num: "4.1.", bold: "Veracidad, Legalidad y Acción Correctiva.", text: " El Usuario es el único responsable de la exactitud, integridad y licitud de todo Contenido del Usuario cargado en la Plataforma. El Usuario garantiza que posee los derechos de propiedad intelectual necesarios sobre dicho contenido y que su procesamiento no infringe derechos de terceros ni normativas de privacidad. En caso de detectar cualquier actividad prohibida, real o inminente, el Usuario se obliga a tomar de inmediato todas las medidas razonables a su alcance para detener dicha actividad y mitigar sus efectos, notificando simultáneamente a la Compañía para coordinar las acciones necesarias." },
      { num: "4.2.", bold: "Responsabilidad Operativa y Requisitos Técnicos.", text: " El Usuario es el único responsable de cumplir con los requisitos técnicos y la documentación operativa proporcionada por la Compañía. El Usuario reconoce que el incumplimiento de dichas especificaciones, incluyendo la resolución de imagen y veracidad de datos, puede causar que los Servicios no funcionen correctamente o resulten en la remoción del contenido. Asimismo, el Usuario asume la responsabilidad total por el uso, seguridad y protección de sus credenciales de acceso contra cualquier uso no autorizado, garantizando que cada suscripción sea utilizada exclusivamente por el Usuario Autorizado designado." },
      { num: "4.3.", bold: "Resultados y Toma de Decisiones.", text: " Todo acceso y uso de los Servicios realizados a través de los sistemas o credenciales del Usuario, incluyendo todos los resultados, conclusiones, decisiones y acciones basadas en dichos Servicios, son responsabilidad exclusiva del Usuario. La Compañía no será responsable por las interpretaciones financieras, proyecciones de inversión o negociaciones inmobiliarias que el Usuario realice basándose en el uso de la Plataforma. El Usuario se compromete a mantener a la Compañía indemne ante cualquier reclamación derivada de decisiones comerciales tomadas a partir de la información gestionada en el ecosistema Brickly." }
    ]
  }
];

const ES_SECTIONS_5_12 = [
  {
    num: "5.",
    title: "TARIFAS Y PAGO",
    items: [
      { num: "5.1.", bold: "Estructura de Cargos y Suscripción.", text: " Los Servicios se prestan bajo un modelo de Membresía o Suscripción con tarifas basadas en períodos mensuales o anuales, según se detalla en la lista de precios vigente en la Plataforma. Las Suscripciones se dividen en niveles que determinan la cantidad de Usuarios Autorizados permitidos; los niveles superiores facultan al Administrador para integrar a un número mayor de colaboradores. El Usuario reconoce que el derecho al cobro de las tarifas por parte de la Compañía es independiente del uso efectivo de los Servicios; la falta de actividad por parte del Usuario no exime de la obligación de pago íntegro. Salvo disposición expresa en contrario, todas las tarifas son no cancelables y no reembolsables." },
      { num: "5.2.", bold: "Ajustes, Usuarios Excedentes y Política de Uso Justo.", text: " La Compañía se reserva el derecho de actualizar la lista de precios o instituir nuevas tarifas, notificando al Usuario antes del inicio de su próximo período de renovación. El número de Usuarios Autorizados adquiridos no podrá disminuir durante el término de la suscripción vigente. Si tras una auditoría periódica la Compañía detecta que el número de Usuarios reales excede el plan contratado, o si se identifica un uso que supere los límites de razonabilidad técnica (Política de Uso Justo), la Compañía facturará de manera proporcional el excedente según el nivel tarifario que corresponda. En caso de no alcanzar un acuerdo sobre dicho exceso en un plazo de treinta (30) días, el Usuario acepta el cargo automático basado en la tarifa del plan superior vigente." },
      { num: "5.3.", bold: "Régimen de Suscripciones y Niveles de Servicio.", text: " Los Servicios de Pago se estructuran bajo un modelo de Suscripción con tarifas calculadas sobre períodos mensuales o anuales, los cuales inician en la fecha de pago inicial y se renuevan de forma automática en cada aniversario del período contratado. Las Suscripciones se comercializan por niveles de servicio; los niveles superiores habilitan la integración de Usuarios Autorizados adicionales hasta el límite establecido en la lista de precios vigente. El Usuario podrá solicitar el aumento de nivel o la adición de Usuarios Autorizados en cualquier momento, lo cual generará un cargo prorrateado por los días restantes del ciclo de facturación actual. No obstante, el número de Usuarios Autorizados contratados no podrá disminuirse durante la vigencia del término de suscripción aplicable. La Compañía se reserva el derecho de auditar periódicamente el volumen de Usuarios activos y, en caso de exceder el plan contratado, se faculta para facturar al Usuario el nivel tarifario correspondiente de manera proporcional al resto del término de la suscripción. Las Suscripciones son reasignables únicamente cuando un nuevo Usuario Autorizado reemplace de forma definitiva a un individuo que cese el uso de los Servicios para cualquier propósito dentro de la organización del Usuario." },
      { num: "5.4.", bold: "Impuestos.", text: " Todas las tarifas y montos publicados por la Compañía se consideran montos netos y no incluyen el Impuesto al Valor Agregado (IVA). La Compañía, como contribuyente registrado en la República de Guatemala, emitirá la Factura Electrónica (FEL) correspondiente por cada pago recibido, adicionando el 12% del IVA sobre el valor neto de los Servicios. El Usuario es responsable de la determinación de sus obligaciones tributarias según su régimen afiliado ante la Superintendencia de Administración Tributaria (SAT). En caso de que el Usuario actúe como Agente de Retención de IVA o ISR, este se obliga a enterar a la Compañía el monto total facturado o, en su defecto, a entregar las constancias de retención legales de forma electrónica e inmediata para la debida conciliación contable de la Compañía. Cualquier otro impuesto, tasa o cargo por servicios digitales que surja de la legislación guatemalteca será asumido íntegramente por el Usuario." },
      { num: "5.5.", bold: "Procesamiento de Pagos y Facturación.", text: " El Usuario deberá realizar todos los pagos a través de la pasarela de pago designada (Stripe u otra plataforma autorizada), aceptando íntegramente los términos y condiciones de dicho proveedor. Las instrucciones de pago se presentarán inmediatamente después de enviado el pedido y la Compañía emitirá la Factura Electrónica (FEL) correspondiente tras la confirmación del mismo. En casos de renovación automática de la Suscripción o cargos por uso excesivo, las tarifas se aplicarán de forma automática al último método de pago registrado por el Usuario." },
      { num: "5.6.", bold: "Incumplimiento de Pago y Mora.", text: " En caso de impago en la fecha de vencimiento, la Compañía podrá, sin perjuicio de otros recursos legales: (a) devengar un interés moratorio sobre el monto vencido a una tasa del 0.5% por cada día de demora, o la tasa máxima permitida por la legislación guatemalteca; y (b) exigir al Usuario el reembolso total de los costos incurridos en la gestión de cobranza, incluyendo honorarios profesionales, costas judiciales y gastos de agencias de recolección." },
      { num: "5.7.", bold: "Gestión de Contracargos.", text: " La Compañía se reserva el derecho de suspender de inmediato y sin previo aviso el acceso a los Servicios ante la notificación de un contracargo (chargeback), el cual será considerado un incumplimiento grave de las obligaciones de pago. La Compañía se faculta para impugnar cualquier contracargo recibido y para restringir permanentemente el acceso al Usuario si se determina que la solicitud fue realizada de forma maliciosa o infundada." },
      { num: "5.8.", bold: "Política de Uso Justo y Excedentes.", text: " El Usuario se obliga a utilizar los Servicios de manera razonable y conforme al número de Usuarios Autorizados contratados. La Compañía se reserva el derecho de intervenir o restringir el acceso si se detecta un uso que exceda los límites de razonabilidad técnica o comercial. A falta de un acuerdo específico dentro de los treinta (30) días posteriores a la detección de un uso excedente, el Usuario acepta pagar las tarifas correspondientes a dicho exceso, calculadas sobre el porcentaje de sobreuso aplicado a la tarifa del plan de Suscripción más alto vigente en ese momento." }
    ]
  },
  {
    num: "6.",
    title: "CONFIDENCIALIDAD",
    items: [
      { num: "6.1.", bold: "Definición y Alcance de la Información Confidencial.", text: " En el marco del presente Acuerdo, las partes podrán intercambiar información técnica, financiera o estratégica, actuando indistintamente como Parte Reveladora o Parte Receptora. Se considera Información Confidencial cualquier dato relativo a la tecnología, secretos comerciales, códigos fuente, algoritmos, metodologías de precios, estrategias de mercado y planes de negocio de la Parte Reveladora. No se considerará confidencial aquella información que: (a) sea de dominio público sin mediar incumplimiento del receptor; (b) fuera conocida por el receptor con anterioridad a su divulgación; o (c) haya sido desarrollada de forma independiente y documentada sin uso de la información de la contraparte." },
      { num: "6.2.", bold: "Protección, Uso Restringido y Revelación Obligada.", text: " La Parte Receptora se obliga a no acceder ni utilizar la Información Confidencial para fines ajenos al cumplimiento de las obligaciones de este Acuerdo. El acceso a dicha información queda limitado exclusivamente a representantes, empleados o asesores que necesiten conocerla por razones operativas y que estén sujetos a acuerdos de confidencialidad con estándares de protección similares a los aquí establecidos. En caso de que una autoridad legal o gubernamental exija la revelación de Información Confidencial, la Parte Receptora notificará de inmediato a la Parte Reveladora y solo divulgará la porción estrictamente requerida por ley." },
      { num: "6.3.", bold: "Uso Analítico Autorizado.", text: " La Compañía se reserva el derecho de procesar y utilizar el Contenido del Usuario para la creación, desarrollo y mantenimiento de una capa analítica de datos agregados (inteligencia de mercado, mapas de calor de precios, tendencias de inventario, entre otros). El Usuario otorga su consentimiento expreso para este uso y reconoce que no tendrá derecho a recibir pagos, regalías, ni compensación de ninguna clase derivado de la explotación comercial de dichos análisis. Se establece de común acuerdo que el uso del Contenido del Usuario para estos fines analíticos no será considerado, bajo ninguna circunstancia, un incumplimiento de las obligaciones de confidencialidad establecidas en este Acuerdo." },
      { num: "6.5.", bold: "Revelaciones Obligadas.", text: " En caso de que la Parte Receptora o cualquiera de sus representantes se vea obligado por la ley aplicable, orden judicial o requerimiento de autoridad competente a divulgar Información Confidencial, la Parte Receptora deberá: (a) limitar la divulgación únicamente a la porción de información que esté legalmente obligada a revelar; y (b) en la medida que la ley lo permita, notificar por escrito y de forma inmediata a la Parte Reveladora sobre dicha obligación para que esta pueda buscar medidas de protección o interponer los recursos legales correspondientes." },
      { num: "6.6.", bold: "Vigencia de la Confidencialidad.", text: " Las obligaciones estipuladas en esta Sección permanecerán vigentes durante toda la duración del Acuerdo y se extenderán por un período de cinco (5) años posteriores a su terminación. No obstante, para aquella información que constituya un secreto comercial bajo la legislación aplicable, la obligación de confidencialidad persistirá de forma indefinida mientras dicha información mantenga tal carácter." }
    ]
  },
  {
    num: "7.",
    title: "CONTENIDO DEL USUARIO",
    items: [
      { num: "7.1.", bold: "Responsabilidad, Veracidad y Garantías del Usuario.", text: " El Usuario asume la responsabilidad total, exclusiva e ilimitada por todo el Contenido (definido como imágenes, descripciones, metadatos, planos, videos y datos técnicos) que cargue, publique o transmita a través de la Plataforma. Al realizar cualquier carga, el Usuario declara, garantiza y se obliga a demostrar, si le fuera requerido, que: (a) es el titular legítimo de los derechos de propiedad intelectual o cuenta con las licencias y autorizaciones notariales necesarias para su difusión pública; (b) el contenido no infringe derechos de privacidad, propiedad industrial o derechos de autor de terceros; y (c) la información proporcionada es veraz, exacta y refleja el estado real y jurídico del inmueble." },
      { num: "7.2.", bold: "Facultades de Control y Moderación de la Compañía.", text: " Si bien el Usuario es el responsable primario de su contenido, la Compañía ejerce un rol de supervisión activa sobre el Contenido del Usuario para garantizar la integridad, estética y profesionalismo del ecosistema Brickly. La Compañía se reserva el derecho de revisar, auditar y validar cada publicación antes o después de su difusión pública. En ejercicio de esta facultad, la Compañía podrá: (a) rechazar contenido que no cumpla con los estándares mínimos de fotografía, descripción o veracidad técnica; (b) solicitar al Usuario documentación adicional que sustente la disponibilidad o legalidad del inmueble; y (c) editar o ajustar formatos para asegurar la homogeneidad visual de la Plataforma. El Usuario reconoce que esta supervisión es una medida de protección para todos los miembros de la red y no exime al Usuario de su responsabilidad final por la veracidad de los datos, ni implica que la Compañía asuma una obligación de garantía frente a terceros por errores u omisiones del Usuario que hayan superado los filtros de revisión." }
    ]
  }
];

const ES_SECTIONS_9_12 = [
  {
    num: "9.",
    title: "INDEMNIZACIÓN",
    items: [
      { num: "9.1.", bold: "Responsabilidad de la Compañía.", text: " La Compañía indemnizará al Usuario por los daños directos derivados de una sentencia final firme y no apelable que resulte de reclamos de terceros alegando que el uso de la Plataforma (excluyendo el Contenido del Usuario y materiales de terceros) infringe derechos de autor. Esta obligación no aplicará si la supuesta infracción se deriva de: (a) el uso de hardware o software no proporcionado por la Compañía; (b) la falta de implementación de actualizaciones sugeridas por la Compañía; o (c) cualquier acto u omisión negligente del Usuario descrito en la sección 9.3." },
      { num: "9.2.", bold: "Mitigación y Continuidad del Servicio.", text: " En caso de que los Servicios sean objeto de una reclamación de propiedad intelectual, o si la Compañía considera que es probable que lo sean, la Compañía podrá, a su entera discreción y costo: (a) obtener el derecho para que el Usuario continúe utilizando los Servicios; (b) modificar la Plataforma para que deje de infringir derechos, manteniendo una funcionalidad equivalente; o (c) rescindir el Acuerdo notificando por escrito al Usuario y solicitando el cese inmediato del uso de la función afectada." },
      { num: "9.3.", bold: "Obligación de Indemnizar del Usuario.", text: " El Usuario se obliga a indemnizar, defender y mantener indemne a la Compañía, sus afiliados, directores, empleados y agentes ante cualquier pérdida, daño, reclamo, multa, penalización o gasto (incluyendo honorarios de abogados y costos judiciales) que surja de: (a) el Contenido del Usuario y su procesamiento por parte de la Compañía conforme a este Acuerdo; (b) el incumplimiento por parte del Usuario de cualquier declaración, garantía u obligación contenida en estos Términos; o (c) cualquier acto de negligencia, dolo o imprudencia por parte del Usuario o sus Usuarios Autorizados." },
      { num: "9.4.", bold: "Procedimiento Detallado de Indemnización.", text: " Cada parte (el Indemnizado) notificará de inmediato y por escrito a la otra parte (el Indemnizador) sobre cualquier acción, demanda o reclamo por el cual crea tener derecho a ser indemnizada. El incumplimiento o demora en la notificación no eximirá al Indemnizador de sus obligaciones, a menos que dicha demora perjudique sustancialmente la defensa de la acción. Tras la notificación: (a) El Indemnizador asumirá de inmediato y de forma exclusiva el control de la defensa y la negociación de cualquier acuerdo, empleando para ello asesores legales externos de reconocido prestigio, sujetos a la aprobación razonable del Indemnizado. (b) El Indemnizado tendrá el derecho (más no la obligación) de participar en la defensa con abogados de su elección a su propio costo. El Indemnizador deberá mantener al Indemnizado plenamente informado de todos los avances, documentos y estrategias del proceso. (c) El Indemnizador no podrá aceptar ninguna responsabilidad, transigir o liquidar ninguna acción sin el consentimiento previo, expreso y por escrito del Indemnizado, especialmente si dicho acuerdo implica una admisión de culpa o impone obligaciones financieras o de cumplimiento al Indemnizado. (d) Si el Indemnizador no asume el control de la defensa dentro de un plazo razonable tras la notificación, o si rechaza su obligación de indemnizar, el Indemnizado tendrá el derecho de asumir su propia defensa y liquidar la acción en los términos que considere apropiados, reservándose el derecho de repetir contra el Indemnizador por todos los costos, honorarios y daños incurridos." }
    ]
  },
  {
    num: "10.",
    title: "LIMITACIÓN DE RESPONSABILIDAD",
    items: [
      { num: "10.1.", bold: "EXCLUSIÓN DE DAÑOS INDIRECTOS Y CONSECUENTES.", text: " EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY APLICABLE, EN NINGÚN CASO LA COMPAÑÍA, SUS AFILIADOS, LICENCIANTES, PROVEEDORES DE SERVICIOS O EMPLEADOS SERÁN RESPONSABLES ANTE EL USUARIO O ANTE CUALQUIER TERCERO BAJO NINGUNA TEORÍA LEGAL O DE EQUIDAD POR: (A) CUALQUIER DAÑO INDIRECTO, INCIDENTAL, ESPECIAL, CONSECUENTE O PUNITIVO; (B) PÉRDIDA DE INGRESOS, LUCRO CESANTE O PÉRDIDA DE BENEFICIOS COMERCIALES; (C) PÉRDIDA DE USO, PÉRDIDA O CORRUPCIÓN DE DATOS, O INTERRUPCIÓN DEL NEGOCIO; (D) COSTOS DE SUSTITUCIÓN DE BIENES O SERVICIOS; O (E) DAÑOS A LA REPUTACIÓN O PÉRDIDA DE FONDO DE COMERCIO (GOODWILL); SURJAN O NO DE LA PRESTACIÓN DE LOS SERVICIOS, INCLUSO SI LA COMPAÑÍA FUE ADVERTIDA DE LA POSIBILIDAD DE TALES DAÑOS O SI DICHOS DAÑOS ERAN PREVISIBLES." },
      { num: "10.2.", bold: "RESPONSABILIDAD POR DECISIONES COMERCIALES.", text: " EL USUARIO RECONOCE Y ACEPTA EXPRESAMENTE QUE LA COMPAÑÍA NO TIENE RESPONSABILIDAD ALGUNA POR LOS RESULTADOS DE LAS TRANSACCIONES INMOBILIARIAS, INVERSIONES O DECISIONES FINANCIERAS TOMADAS POR EL USUARIO BASADAS EN EL USO DE LOS SERVICIOS O LA CAPA ANALÍTICA DE LA PLATAFORMA. LA COMPAÑÍA NO GARANTIZA EL CIERRE DE VENTAS, LA RENTABILIDAD DE LOS PROYECTOS NI LA EXACTITUD DE LOS DATOS PROPORCIONADOS POR OTROS USUARIOS O TERCEROS." },
      { num: "10.3.", bold: "LÍMITE MÁXIMO DE RESPONSABILIDAD ECONÓMICA.", text: " EN NINGÚN CASO LA RESPONSABILIDAD TOTAL AGREGADA DE LA COMPAÑÍA Y SUS AFILIADOS QUE SURJA DE O ESTÉ RELACIONADA CON ESTE ACUERDO, BAJO CUALQUIER TEORÍA LEGAL, EXCEDERÁ EL MONTO QUE SEA MENOR ENTRE: (A) EL MONTO TOTAL PAGADO POR EL USUARIO A LA COMPAÑÍA POR LOS SERVICIOS DURANTE LOS DOCE (12) MESES INMEDIATAMENTE ANTERIORES AL EVENTO QUE DIO LUGAR A LA RECLAMACIÓN; O (B) LA CANTIDAD TOTAL DE SETENTA Y CINCO DÓLARES DE LOS ESTADOS UNIDOS DE AMÉRICA ($75.00). ESTA LIMITACIÓN ES ACUMULATIVA Y NO POR INCIDENTE." }
    ]
  },
  {
    num: "11.",
    title: "PLAZO Y TERMINACIÓN",
    items: [
      { num: "11.1.", bold: "Vigencia y Renovación Automática.", text: " El Acuerdo se celebra por un período de tiempo indefinido. La terminación del Acuerdo implica automáticamente la terminación de cualquier Suscripción activa. El término inicial de la Suscripción comienza en la fecha de confirmación del pedido y continuará durante el período contratado. La Suscripción se renovará automáticamente por períodos sucesivos de igual duración al anterior, a menos que: (a) se termine anticipadamente bajo las disposiciones de este Acuerdo; o (b) cualquiera de las partes notifique por escrito su intención de no renovar, a más tardar el último día del término actual. Cada renovación está sujeta al pago previo de las tarifas vigentes." },
      { num: "11.2.", bold: "Causales de Terminación.", text: " Además de otros derechos establecidos en el Acuerdo, las partes podrán darlo por terminado bajo las siguientes condiciones: (a) Por Incumplimiento Material: Cualquiera de las partes puede terminar el Acuerdo si la otra parte incumple materialmente sus obligaciones y dicho incumplimiento no es subsanado dentro de los treinta (30) días posteriores a la notificación por escrito. (b) Por Facultad Exclusiva de la Compañía: La Compañía podrá terminar el Acuerdo de forma inmediata y mediante aviso escrito si el Usuario: (i) incurre en mora o falta de pago de cualquier monto adeudado; (ii) infringe las Restricciones de Uso o Propiedad Intelectual (Secciones 3 y 4); o (iii) es objeto de una petición de quiebra, insolvencia, intervención judicial o cesión de bienes a favor de acreedores." },
      { num: "11.3.", bold: "Efectos de la Terminación.", text: " Al vencimiento o terminación del Acuerdo, se aplicarán las siguientes reglas: (a) Cese de Derechos: Todos los derechos y licencias otorgados al Usuario cesarán de forma inmediata y el Usuario deberá interrumpir todo uso de los Servicios. (b) Gestión de Cuenta y Contenido: El Usuario podrá solicitar la cancelación de su cuenta. La Compañía desactivará la visualización pública del Contenido del Usuario, pero retendrá la facultad de conservar dichos datos en sus sistemas. Bajo ninguna circunstancia la Compañía estará obligada a eliminar los Datos Resultantes, los cuales seguirán siendo de su propiedad exclusiva. (c) Liquidación de Tarifas: Si el Acuerdo termina por causa imputable al Usuario (incluyendo falta de pago), todas las tarifas que habrían sido exigibles hasta la expiración del término de suscripción actual se volverán inmediatamente exigibles y pagaderas. (d) Acceso de Usuarios: La Compañía desactivará el acceso de todos los Usuarios Autorizados en un plazo máximo de quince (15) días tras la terminación." },
      { num: "11.4.", bold: "Términos que Perduran.", text: " Todas las disposiciones que por su naturaleza deban sobrevivir a la terminación para surtir efecto, continuarán vigentes, incluyendo pero no limitado a: Confidencialidad, Propiedad Intelectual, Indemnización, Limitación de Responsabilidad, Datos Resultantes y Ley Aplicable." }
    ]
  },
  {
    num: "12.",
    title: "DISPOSICIONES GENERALES",
    items: [
      { num: "12.1.", bold: "Acuerdo Completo y Jerarquía.", text: " Los presentes Términos, junto con cualquier Formulario de Pedido aceptado, constituyen la totalidad de los acuerdos entre el Usuario y la Compañía, sustituyendo cualquier negociación o comunicación previa. En caso de existir discrepancias entre distintos documentos del Acuerdo, prevalecerá lo establecido en estos Términos de Servicio, seguidos por los anexos técnicos en su orden de publicación." },
      { num: "12.2.", bold: "Fuerza Mayor y Exoneración de Responsabilidad.", text: " Brickly no será responsable por fallas o retrasos en el Servicio derivados de circunstancias fuera de su control razonable (casos fortuitos o de fuerza mayor). Esto incluye, pero no se limita a: actos de la naturaleza, desastres naturales, incendios, terremotos, inundaciones, guerras, terrorismo, embargos, huelgas, cierres gubernamentales, escasez de energía o fallas masivas en las telecomunicaciones. Especialmente, se consideran fuerza mayor los ciberataques de terceros (como ataques DDoS) que superen las medidas de seguridad estándar. Si el evento de fuerza mayor persiste por más de sesenta (60) días, Brickly podrá dar por terminado el Acuerdo sin penalidad alguna." },
      { num: "12.3.", bold: "Cesión y Transferencia de Derechos.", text: " El Usuario tiene prohibido ceder, delegar o transferir sus derechos u obligaciones derivados de este Acuerdo sin el consentimiento previo y por escrito de la Compañía. No obstante, la Compañía podrá ceder o transferir la totalidad de este Acuerdo, sin necesidad de consentimiento previo del Usuario, a cualquiera de sus Afiliadas, subsidiarias o a un tercero en caso de fusión, adquisición o venta de activos de Brickly." },
      { num: "12.4.", bold: "Divisibilidad y Preservación del Acuerdo.", text: " Si cualquier disposición de este Acuerdo fuera declarada nula, ilegal o inaplicable por una autoridad competente, dicha nulidad no afectará la validez de las demás cláusulas. Las partes se comprometen a negociar de buena fe para sustituir la disposición afectada por una válida que refleje lo más fielmente posible la intención comercial original." },
      { num: "12.5.", bold: "Enmiendas y Actualizaciones.", text: " La Compañía se reserva el derecho de revisar y actualizar estos Términos a su entera discreción. Los cambios entrarán en vigor en la fecha de su publicación en la Plataforma. El uso continuo de los Servicios por parte del Usuario tras dicha actualización constituye su aceptación vinculante. Es responsabilidad del Usuario revisar periódicamente los Términos para mantenerse informado sobre las condiciones vigentes." },
      { num: "12.6.", bold: "Notificaciones y Validez Electrónica.", text: " Las partes acuerdan que el requisito de forma escrita se cumple mediante el intercambio de comunicaciones por correo electrónico u otros medios electrónicos habilitados en la Plataforma. Las notificaciones se considerarán entregadas cuando se envíen a la dirección de correo electrónico registrada por el Usuario o la publicada oficialmente por la Compañía." },
      { num: "12.7.", bold: "Ley Aplicable y Resolución de Disputas.", text: " El presente Acuerdo se rige e interpreta exclusivamente bajo las leyes de la República de Guatemala. Para la resolución de cualquier controversia o disputa derivada de estos Términos, las partes renuncian expresamente a cualquier otro fuero y se someten a la jurisdicción de los juzgados y tribunales civiles de la Ciudad de Guatemala." }
    ]
  }
];

const EN_SECTIONS_2_12 = [
  {
    num: "2.",
    title: "SERVICES AND ACCESS CONDITIONS",
    items: [
      { num: "2.1.", bold: "User Classification.", text: " Access to the Platform is governed by the following categories: (a) Free Users, who use the basic version of the Services with access to a limited set of features compared to Authorized Users, and may obtain access to extended functionalities by acquiring specific Paid Services; and (b) Authorized Users, who use the Platform as part of a paid Subscription plan. This latter category is subdivided into Administrators, with authority to manage the subscription and supervise the activities of other users within their organization, and Regular Authorized Users, with authority to publish and manage inventory, always subject to compliance with the Company's technical specifications." },
      { num: "2.2.", bold: "License of Use and Publication Standards.", text: " Subject to strict compliance with this Agreement, the Company grants the User a limited, revocable, non-exclusive, and non-transferable license to use the Services. The User agrees that all uploaded Content must strictly comply with Brickly's technical specifications, which include, but are not limited to: (i) minimum image resolution of 1920x1080 pixels, (ii) complete absence of third-party watermarks, and (iii) verifiable accuracy of the property's technical data. Non-compliance with these specifications shall be considered use outside the scope of the granted license, entitling the Company to remove the content or suspend access." },
      { num: "2.3.", bold: "Intellectual Property and Reservation of Rights.", text: " The Company is the sole and exclusive owner of all rights, titles, and interests in the Platform and Services, including software, source code, data processing algorithms, recommendation systems, database architecture, interface design (UX/UI), graphic elements, and integrated financial analysis methodologies. The User is strictly prohibited from reverse engineering, decompiling, or attempting to extract the source code of the Platform. Likewise, automated data extraction (scraping) by robots or external software is prohibited, as is the creation of derivative works that compete with the Platform using elements owned by the Company." },
      { num: "2.4.", bold: "Regime of Resulting Data.", text: " By virtue of the analytical capacity of the Platform, the User acknowledges that the Company generates strategic information from the use of the Services. Ownership of these Resulting Data, comprising statistical data, market trends, transaction volumes, and analytical behavior, belongs exclusively to the Company. The User irrevocably and perpetually assigns any rights over such data, authorizing the Company to commercially exploit them for market intelligence reports, cost model optimization, and operational performance improvement." },
      { num: "2.5.", bold: "Suspension and Termination of Services.", text: " The Company reserves the right to immediately suspend, rescind, or deny access to and use of the Platform to any User, without incurring any obligation, liability, or right to compensation, when any of the following circumstances arise: (a) strict compliance with a judicial, administrative, or governmental order, or in response to legislative and regulatory changes that render the provision of Services unlawful or impracticable; (b) the Company's discretionary determination that the User has breached any provision of this Agreement, exceeded the scope of the granted license, or used the Platform for unauthorized, fraudulent, or illegal purposes that compromise the integrity of the ecosystem; and (c) non-payment of applicable fees on their due dates or upon receipt of chargeback notifications and financial disputes related to the User's account, in which case the suspension shall persist until the definitive resolution of the incident to the Company's full satisfaction." }
    ]
  },
  {
    num: "3.",
    title: "USE RESTRICTIONS",
    items: [
      { num: "3.1.", bold: "Use Restrictions.", text: " The User is prohibited from allowing any person to access or use the Services, except as expressly provided in this Agreement. In particular, but not exclusively, the User agrees: (a) not to make the Services available to unauthorized third parties or use them for the benefit of persons outside their organization or affiliates; (b) to refrain from renting, sublicensing, reselling, assigning, distributing, or commercially exploiting the Services, including the practice of allowing employees or collaborators to access as guests to circumvent the acquisition of individual Subscriptions; (c) not to reverse engineer, copy, modify, adapt, hack, or interfere with the integrity of the Services; (d) not to access the Services, documentation, or confidential information of the Company for the purpose of building, designing, or promoting a competitive product or service; (e) not to share access credentials among multiple individuals, except for the formal reassignment of a subscription to a new Authorized User who definitively replaces a previous one; (f) not to damage, disable, overload, or impair the technological infrastructure or the provision of Services by the Company; and (g) not to use the Platform for purposes that infringe third-party intellectual property rights or any applicable legislation." },
      { num: "3.2.", bold: "Sanctions.", text: " The Services are offered exclusively to users who are not subject to any international sanctions regime and who do not reside in or access the Platform from jurisdictions where such access is prohibited by export control laws or international treaties. By using the Services, the User declares and warrants compliance with these requirements. The Company reserves the right to limit, restrict, or block at any time the availability of the Services to any person, entity, geographic area, or specific jurisdiction to ensure legal compliance and operational integrity." }
    ]
  },
  {
    num: "4.",
    title: "USER OBLIGATIONS",
    items: [
      { num: "4.1.", bold: "Accuracy, Legality, and Corrective Action.", text: " The User assumes sole, exclusive, and unlimited responsibility for the accuracy, completeness, and lawfulness of all User Content uploaded to the Platform. The User warrants that they hold the necessary intellectual property rights over such content and that its processing does not infringe third-party rights or privacy regulations. Upon detecting any prohibited activity, actual or imminent, the User agrees to immediately take all reasonable measures available to stop such activity and mitigate its effects, simultaneously notifying the Company to coordinate necessary actions." },
      { num: "4.2.", bold: "Operational Responsibility and Technical Requirements.", text: " The User is solely responsible for complying with the technical requirements and operational documentation provided by the Company. The User acknowledges that non-compliance with such specifications, including image resolution and data accuracy, may cause the Services to malfunction or result in content removal. Likewise, the User assumes full responsibility for the use, security, and protection of their access credentials against any unauthorized use, ensuring that each subscription is used exclusively by the designated Authorized User." },
      { num: "4.3.", bold: "Results and Decision-Making.", text: " All access to and use of the Services through the User's systems or credentials, including all results, conclusions, decisions, and actions based on such Services, are the exclusive responsibility of the User. The Company shall not be liable for financial interpretations, investment projections, or real estate negotiations that the User makes based on the use of the Platform. The User agrees to hold the Company harmless from any claim arising from commercial decisions made based on information managed in the Brickly ecosystem." }
    ]
  },
  {
    num: "5.",
    title: "FEES AND PAYMENT",
    items: [
      { num: "5.1.", bold: "Fee Structure and Subscription.", text: " The Services are provided under a Membership or Subscription model with fees based on monthly or annual periods, as detailed in the current price list on the Platform. Subscriptions are divided into tiers that determine the number of permitted Authorized Users; higher tiers authorize the Administrator to integrate a greater number of collaborators. The User acknowledges that the Company's right to collect fees is independent of the actual use of the Services; lack of activity by the User does not exempt them from the obligation of full payment. Unless expressly stated otherwise, all fees are non-cancellable and non-refundable." },
      { num: "5.2.", bold: "Adjustments, Excess Users, and Fair Use Policy.", text: " The Company reserves the right to update the price list or institute new fees, notifying the User before the start of their next renewal period. The number of Authorized Users acquired may not decrease during the term of the current subscription. If after a periodic audit the Company detects that the number of actual Users exceeds the contracted plan, or if use exceeding the limits of technical reasonableness is identified (Fair Use Policy), the Company will proportionally invoice the excess according to the applicable rate tier. If no agreement is reached on such excess within thirty (30) days, the User accepts the automatic charge based on the current higher plan rate." },
      { num: "5.3.", bold: "Subscription Regime and Service Levels.", text: " Paid Services are structured under a Subscription model with fees calculated on monthly or annual periods, which begin on the initial payment date and automatically renew on each anniversary of the contracted period. Subscriptions are sold by service tiers; higher tiers enable the integration of additional Authorized Users up to the limit established in the current price list. The User may request a tier upgrade or the addition of Authorized Users at any time, which will generate a prorated charge for the remaining days of the current billing cycle. However, the number of contracted Authorized Users may not be reduced during the applicable subscription term." },
      { num: "5.4.", bold: "Taxes.", text: " All fees and amounts published by the Company are considered net amounts and do not include Value Added Tax (VAT). The Company, as a registered taxpayer in the Republic of Guatemala, will issue the corresponding Electronic Invoice (FEL) for each payment received, adding 12% VAT to the net value of the Services. The User is responsible for determining their tax obligations according to their registered regime with the Tax Administration Superintendency (SAT)." },
      { num: "5.5.", bold: "Payment Processing and Invoicing.", text: " The User must make all payments through the designated payment gateway (Stripe or other authorized platform), fully accepting the terms and conditions of said provider. Payment instructions will be presented immediately after the order is submitted and the Company will issue the corresponding Electronic Invoice (FEL) upon confirmation. In cases of automatic Subscription renewal or charges for excessive use, fees will be automatically applied to the last payment method registered by the User." },
      { num: "5.6.", bold: "Payment Default and Late Fees.", text: " In case of non-payment on the due date, the Company may, without prejudice to other legal remedies: (a) accrue late interest on the overdue amount at a rate of 0.5% per day of delay, or the maximum rate permitted by Guatemalan law; and (b) require the User to fully reimburse costs incurred in collection management, including professional fees, court costs, and collection agency expenses." },
      { num: "5.7.", bold: "Chargeback Management.", text: " The Company reserves the right to immediately and without prior notice suspend access to the Services upon notification of a chargeback, which shall be considered a serious breach of payment obligations. The Company is authorized to contest any received chargeback and to permanently restrict the User's access if the request is determined to have been made maliciously or without merit." },
      { num: "5.8.", bold: "Fair Use Policy and Excess.", text: " The User agrees to use the Services reasonably and in accordance with the number of contracted Authorized Users. The Company reserves the right to intervene or restrict access if use exceeding the limits of technical or commercial reasonableness is detected. In the absence of a specific agreement within thirty (30) days of detecting excess use, the User agrees to pay the fees corresponding to such excess, calculated on the percentage of overuse applied to the highest current Subscription plan rate." }
    ]
  },
  {
    num: "6.",
    title: "CONFIDENTIALITY",
    items: [
      { num: "6.1.", bold: "Definition and Scope of Confidential Information.", text: " Under this Agreement, the parties may exchange technical, financial, or strategic information, acting interchangeably as Disclosing Party or Receiving Party. Confidential Information includes any data relating to technology, trade secrets, source codes, algorithms, pricing methodologies, market strategies, and business plans of the Disclosing Party. Information shall not be considered confidential if: (a) it is in the public domain without breach by the recipient; (b) it was known to the recipient prior to its disclosure; or (c) it was independently developed and documented without use of the counterparty's information." },
      { num: "6.2.", bold: "Protection, Restricted Use, and Mandatory Disclosure.", text: " The Receiving Party agrees not to access or use Confidential Information for purposes other than fulfilling the obligations of this Agreement. Access to such information is limited exclusively to representatives, employees, or advisors who need to know it for operational reasons and who are subject to confidentiality agreements with similar protection standards. If a legal or governmental authority requires disclosure of Confidential Information, the Receiving Party shall immediately notify the Disclosing Party and only disclose the portion strictly required by law." },
      { num: "6.3.", bold: "Authorized Analytical Use.", text: " The Company reserves the right to process and use User Content for the creation, development, and maintenance of an analytical layer of aggregated data (market intelligence, price heat maps, inventory trends, among others). The User expressly consents to this use and acknowledges that they shall have no right to receive payments, royalties, or compensation of any kind derived from the commercial exploitation of such analyses. This use shall not be considered a breach of confidentiality." },
      { num: "6.5.", bold: "Mandatory Disclosures.", text: " If the Receiving Party or any of its representatives is required by applicable law, court order, or competent authority requirement to disclose Confidential Information, the Receiving Party shall: (a) limit disclosure only to the portion of information legally required; and (b) to the extent permitted by law, immediately notify the Disclosing Party in writing so that it may seek protective measures or file appropriate legal remedies." },
      { num: "6.6.", bold: "Duration of Confidentiality.", text: " The obligations stipulated in this Section shall remain in force throughout the duration of the Agreement and shall extend for a period of five (5) years after its termination. However, for information that constitutes a trade secret under applicable law, the confidentiality obligation shall persist indefinitely as long as such information retains that character." }
    ]
  },
  {
    num: "7.",
    title: "USER CONTENT",
    items: [
      { num: "7.1.", bold: "User Responsibility, Accuracy, and Warranties.", text: " The User assumes total, exclusive, and unlimited responsibility for all Content (defined as images, descriptions, metadata, floor plans, videos, and technical data) that they upload, publish, or transmit through the Platform. When making any upload, the User declares, warrants, and agrees to demonstrate, if required, that: (a) they are the legitimate holder of intellectual property rights or have the necessary licenses and notarial authorizations for public dissemination; (b) the content does not infringe privacy rights, industrial property, or third-party copyrights; and (c) the information provided is truthful, accurate, and reflects the actual and legal status of the property." },
      { num: "7.2.", bold: "Company Control and Moderation Powers.", text: " While the User is the primary responsible party for their content, the Company exercises an active supervisory role over User Content to ensure the integrity, aesthetics, and professionalism of the Brickly ecosystem. The Company reserves the right to review, audit, and validate each publication before or after its public dissemination. In exercising this authority, the Company may: (a) reject content that does not meet minimum photography, description, or technical accuracy standards; (b) request additional documentation from the User to support the availability or legality of the property; and (c) edit or adjust formats to ensure visual homogeneity of the Platform." },
      { num: "7.3.", bold: "Extended License and Exploitation Rights.", text: " The User retains ownership of their copyrights. However, by uploading content to the Services, the User grants the Company an irrevocable, royalty-free, non-exclusive, worldwide, transferable, and sublicensable license for the full duration of legal protection of such rights. This license authorizes the Company to: (a) reproduce, distribute, modify, and display the content to operate and improve the Platform; (b) use the content in accordance with the analytical layer; and (c) use any image or data without limitation in marketing materials, digital advertising, social media, and corporate presentations, without generating any payment obligation or royalties." }
    ]
  },
  {
    num: "12.",
    title: "GENERAL PROVISIONS",
    items: [
      { num: "12.1.", bold: "Entire Agreement and Hierarchy.", text: " These Terms, together with any accepted Order Form, constitute the entire agreement between the User and the Company, superseding any prior negotiations or communications. In case of discrepancies, these Terms of Service shall prevail over technical annexes or previous communications." },
      { num: "12.2.", bold: "Force Majeure and Liability Exemption.", text: " Brickly shall not be liable for failures or delays in the Service arising from circumstances beyond its reasonable control (force majeure). This includes, but is not limited to: acts of nature, fires, earthquakes, floods, wars, terrorism, embargoes, strikes, government shutdowns, energy shortages, or massive telecommunications failures. Cyberattacks (such as DDoS attacks) that exceed standard security measures are specifically considered force majeure. If the event persists for more than sixty (60) days, Brickly may terminate the Agreement without penalty." },
      { num: "12.3.", bold: "Assignment and Transfer of Rights.", text: " The User is prohibited from assigning, delegating, or transferring their rights or obligations under this Agreement without the prior written consent of the Company. The Company may assign or transfer this Agreement to any of its Affiliates or a third party in the event of a merger, acquisition, or sale of assets." },
      { num: "12.4.", bold: "Severability.", text: " If any provision of this Agreement is declared null, illegal, or unenforceable by a competent authority, such nullity shall not affect the validity of the remaining clauses. The parties agree to negotiate in good faith to replace the affected provision with one that reflects the original commercial intent." },
      { num: "12.7.", bold: "Applicable Law and Dispute Resolution.", text: " This Agreement is governed by and construed under the laws of the Republic of Guatemala. For the resolution of any dispute, the parties expressly waive any other jurisdiction and submit to the jurisdiction of the civil courts of Guatemala City." }
    ]
  }
];

// ── Merge all sections ────────────────────────────────────────
const ES_ALL = { ...ES, sections: [...ES.sections, ...ES_SECTIONS_2_12, ...ES_SECTIONS_5_12, ...ES_SECTIONS_9_12] };
const EN_ALL = { ...EN, sections: [...EN.sections, ...EN_SECTIONS_2_12] };

// ── Component ─────────────────────────────────────────────────
function Document() {
  const t = useT();
  const lang = t('es', 'en');
  const data = lang === 'en' ? EN_ALL : ES_ALL;

  const navigate = useNavigate() 

  return (
    <Container className='mb-5' style={{ fontFamily: 'inherit', fontSize: '15px', lineHeight: 1.8}}>

      <div className="d-flex justify-content-end">
        <Link to="" onClick={() => navigate(-1) } className='d-block mb-4 text-end' title={t('Atrás', 'Back')}><img src={arrow} style={{ width: 'clamp(30px, 5vw, 40px)' }} alt={t('Atrás', 'Back')} srcSet="" /></Link>
      </div>

      {/* Title */}
      <h1 style={{ textAlign: 'center', fontWeight: 700, fontSize: 'clamp(20px, 3vw, 26px)', marginBottom: '1.5rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
        {data.title}
      </h1>

      {/* Intro */}
      <p style={{ marginBottom: '2rem', textAlign: 'justify' }}>{data.intro}</p>

      {/* Sections */}
      {data.sections.map((section, si) => (
        <div key={si} style={{ marginBottom: '2rem' }}>
          <h2 style={{ fontWeight: 700, fontSize: 'clamp(15px, 2.5vw, 18px)', marginBottom: '0.75rem', textTransform: 'uppercase' }}>
            {section.num} {section.title}
          </h2>
          {section.intro && <p style={{ marginBottom: '0.75rem', textAlign: 'justify' }}>{section.intro}</p>}
          {section.items.map((item, ii) => (
            <p key={ii} style={{ marginBottom: '0.75rem', textAlign: 'justify' }}>
              <strong>{item.num} {item.bold}</strong>{item.text}
            </p>
          ))}
        </div>
      ))}
    </Container>
  );
}

export default Document;
