version: "3.9"

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_devserver
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads

      - ./data-nestjs/log:/var/log/nestjs/
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge